spring.application.name=recruitment-service
server.port=8082

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:xplore
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console (optional - for viewing database)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true

# External Service URL
interviewer.service.url=${INTERVIEWER_SERVICE_URL:http://localhost:8081/api/slots}



# Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.client=DEBUG
logging.level.com.xplore=DEBUG

