spring.application.name=recruitment-service
server.port=8082

# MySQL DataSource
spring.datasource.url=jdbc:mysql://localhost:3306/xplore?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Osama@9326
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# External Service URL
interviewer.service.url=http://localhost:8081/api/slots


# Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.client=DEBUG
logging.level.com.xplore=DEBUG


